### PR TITLE
safe level 4 is obsolete on ruby 2.1.x

### PR DESCRIPTION
**Pull request by tim-saki**
I'd like to use twowaysql on ruby 2.1.x.
https://bugs.ruby-lang.org/issues/8468

### CODE REVIEW

**Comment by twada** [comment]
LGTM. Thanks!

**Comment by twada** [comment]
Thanks @tim-saki, I'll cut a new release soon.

**Comment by twada** [comment]
Just released [0.6.0](https://rubygems.org/gems/twowaysql). Thanks!

**Comment by tim-saki** [comment]
Thanks!!

**Pull request merged**
